dialer/urls.py
from django.conf.urls.defaults import *
from dialer import views

urlpatterns = patterns('',
    url(
        r'^$',
        views.start,
        {},
        name='dialer_start',
    ),
    
    url(
        r'^dialed/$',
        views.dialed,
        {},
        name='dialer_dialed',
    ),
    
    url(
        r'^conf$',
        views.conf,
        {},
        name='dialer_conf',
    ),
    
    url(
        r'^conf/(?P<confid>\d+)/(?P<from_name>[\w\s]+)/(?P<to_name>[\w\s]+)/$',
        views.conf,
        {},
        name='dialer_confxml',
    ),
)

urls.py
from django.conf.urls.defaults import *
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'peoplepatcher.views.index', name='index'),
    
    url(r'^dialer/', include('dialer.urls'), name='dialer'),
    
    url(r'^autodialer/', include('autodialer.urls'), name='autodialer'),
    
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),
)

dialer/models.py
from datetime import datetime
from django.db import models

class Call(models.Model):
    name1 = models.CharField(max_length=30, blank=True, null=True)
    number1 = models.CharField(max_length=19)
    sid1 = models.CharField(max_length=35, default='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')
    name2 = models.CharField(max_length=30, blank=True, null=True)
    number2 = models.CharField(max_length=19)
    sid2 = models.CharField(max_length=35, default='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')
    creation_date = models.DateTimeField(default=datetime.now)
    
    def __unicode__(self):
        """
        Returns the numbers dialed
        """
        return '{0}[{1}] <-> {2}[{3}]'.format(self.name1,
                                              self.number1,
                                              self.name2,
                                              self.number2)

dialer/forms.py
from django import forms
from django.contrib.localflavor.us.forms import USPhoneNumberField 
from dialer.models import Call

class DialerForm(forms.ModelForm):
    """
    A simple form for creating a new dial
    """
    name1 = forms.CharField(max_length=50, label='First friend', required=False)
    number1 = USPhoneNumberField(max_length=19, label = 'ph #')
    name2 = forms.CharField(max_length=50, label='Second friend', required=False)
    number2 = USPhoneNumberField(max_length=19, label = 'ph #')

    class Meta:
        model = Call
        fields = ('name1', 'number1', 'name2', 'number2')

dialer/views.py
from django.http import HttpResponseBadRequest
from django.shortcuts import redirect, render_to_response
from django.template import RequestContext
from django.views.decorators.csrf import csrf_exempt

from dialer.forms import DialerForm
from dialer.util import add_to_conference

def start(request):
    """
    Renders a form for starting a new dial
    """
    form = DialerForm(request.POST or None)
    if form.is_valid():
        call = form.save()
        call.sid1 = add_to_conference(call.id, call.number1, call.name1, call.name2)
        call.sid2 = add_to_conference(call.id, call.number2, call.name2, call.name1)
        call.save()
        
        return redirect('dialer_dialed')
    
    return render_to_response(
        'dialer/start.html',
        {'form': form},
        context_instance = RequestContext(request)
    )

def dialed(request):
    return render_to_response(
        'dialer/dialed.html',
        {},
        context_instance = RequestContext(request)
    )

def conf(request):
    return render_to_response(
        'dialer/conf.xml',
        {'confid': request.GET.get('confid', ''),
         'from_name': request.GET.get('from_name', ''),
         'to_name': request.GET.get('to_name', ''),},
        context_instance = RequestContext(request)
    )

views.py
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect

def index(request):
    """
    redirect to the dialer
    """
    return HttpResponseRedirect(reverse('dialer_start'))

templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Strict//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
    <head>
        <title>{% block title %}People Patcher{% endblock %}</title>
        <link rel="stylesheet" type="text/css" media="all" href="{{ MEDIA_URL }}css/blitzer/jquery-ui-1.8.4.custom.css" /> 
        <link rel="stylesheet" type="text/css" media="all" href="{{ MEDIA_URL }}css/reset.css" />
        <link rel="stylesheet" type="text/css" media="all" href="{{ MEDIA_URL }}css/text.css" />
        <link rel="stylesheet" type="text/css" media="all" href="{{ MEDIA_URL }}css/960.css" />
        <link rel="stylesheet" type="text/css" media="all" href="{{ MEDIA_URL }}css/screen.css" />
        <!-- Scripts -->
        <script type="text/javascript" src="http://code.jquery.com/jquery-1.4.2.min.js"></script>
        <script type="text/javascript" src="{{ MEDIA_URL }}js/jquery-ui-1.8.4.custom.min.js"></script>
        <script type="text/javascript" src="{{ MEDIA_URL }}js/global.js"></script>
        {% block extra_head %}{% endblock %}
    </head>
    
    <body>
        <div class="container_12">
            <!-- Nav header -->
            <div id="nav_bg">
                <div class="grid_4"><p id="logo"><a href="/">People Patcher</a></p></div>
                <div class="grid_8">
                    <ul id="nav">
                        <li><a href="http://www.cleverkoala.com">Blog</a></li>
                        <li><a href="mailto:mike@cleverkoala.com">Contact</a></li>
                    </ul>
                </div>
                <div class="clear"></div>
            </div>
            
            <!-- Messages -->
            {% block messages %}
                {% if messages %}
                    <ul class="messages grid_12">
                        {% for message in messages %}
                        <li><span>{{ message }}</span></li>
                        {% endfor %}
                    </ul>
                {% endif %}
            {% endblock %}
            
            <!-- Content -->
            <div id="content" class="grid_12">
                {% block main_content %}{% endblock %}
            </div>
        </div>
        
        <!-- Footer -->
        <div class="clear">&nbsp;</div>
        <div id="footer">
	        <ul>
	            <li><span><a href="http://www.CleverKoala.com">&copy; 2010 Clever Koala Software</a></span></li>
	        </ul>
        </div>
        
        <!-- Tracking -->
		<script type="text/javascript">
			var pkBaseURL = (("https:" == document.location.protocol) ? "https://piwik.cleverkoala.com/" : "http://piwik.cleverkoala.com/");
			document.write(unescape("%3Cscript src='" + pkBaseURL + "piwik.js' type='text/javascript'%3E%3C/script%3E"));
		</script>
		<script type="text/javascript">
			try {
				var piwikTracker = Piwik.getTracker(pkBaseURL + "piwik.php", 3);
				piwikTracker.trackPageView();
				piwikTracker.enableLinkTracking();
			} catch( err ) {}
		</script>
		<noscript><p><img src="http://piwik.cleverkoala.com/piwik.php?idsite=3" style="border:0" alt="" /></p></noscript>
        
        <!-- Extra body stuff -->
        {% block extra_body %}{% endblock %}
    </body>
</html>

templates/dialer/dialed.html
{% extends "base.html" %}

{% block main_content %}
<div id="dialed">
    <h1>Your numbers were dialed</h1>
    <p>(Let's hope they pick up.)</p>
    <p>Thanks for using PeoplePatcher.</p>
    
    <br/>
    <div><em><strong><a href="http://www.CleverKoala.com">Clever Koala Software</a></strong></em></div>
    <br/>
    <br/>
    <div><em><a href="..">back home</a></em></div>
</div>
{% endblock %}

templates/dialer/start.html
{% extends "base.html" %}

{% block main_content %}

<script type="text/javascript">
    $(function() {
        $("input.submit").button();
        $("input.submit").show();
    });
</script>

<div id="grabber" class="container_12"></div>
<div class='clear'>&nbsp;</div> 

<div id="calltoaction" class="container_12">
    <div id="steps" class="grid_5"></div>
    <div id="callform" class="grid_7">
		<form method="POST" action="">
		    <div class="callentry">
		      <label for="id_name1">Name:</label>
              {{ form.name1 }}
              <strong>
	              {% if form.number1.errors %}
			          <em><label for="id_number1">*Number:</label></em>
			      {% else %}
			          <label for="id_number1">*Number:</label>
			      {% endif %}
		      </strong>
              {{ form.number1 }}
		    </div>
		    
		    <h1>...should patch it up with...</h1>
            <div class="callentry">
              <label for="id_name2">Name:</label>
              {{ form.name2 }}
              <strong>
	              {% if form.number1.errors %}
	                  <em><label for="id_number2">*Number:</label></em>
	              {% else %}
	                  <label for="id_number2">*Number:</label>
	              {% endif %}
              </strong>
              {{ form.number2 }}
            </div>
		    
            {% if form.number1.errors or form.number2.errors %}
                <div class="formerrors">Error! Number(s) not valid!</div>
            {% endif %}
            
		    <div>
		      <input class="submit" type="submit" value="Patch!" style="display:none" />
		      <h5>(It's 100% free!)</h5>
		    </div>
		    
	        <div class="note">
	            <p>*Sorry, US numbers only right now.</p>
	        </div>
	        
            {% csrf_token %}
		</form>
		
	</div>
</div>
{% endblock %}